import config


class Configuration:
    DEBUG = getattr(config, 'DEBUG', True)
    SQLALCHEMY_DATABASE_URI = config.SQLALCHEMY_DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = getattr(config, 'SQLALCHEMY_TRACK_MODIFICATIONS', False)
    SECRET_KEY = config.SECRET_KEY
    SECURITY_PASSWORD_SALT = config.SECURITY_PASSWORD_SALT
    SECURITY_PASSWORD_HASH = config.SECURITY_PASSWORD_HASH
