"""empty message

Revision ID: 5368020c1a4f
Revises: 9add51315226
Create Date: 2023-06-28 16:13:45.874278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5368020c1a4f'
down_revision = '9add51315226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('period_in_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'period_in_months')
    # ### end Alembic commands ###
