"""empty message

Revision ID: 9add51315226
Revises: 8c014c182d99
Create Date: 2023-06-26 15:25:13.851568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9add51315226'
down_revision = '8c014c182d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain', sa.Column('tx_hash_api_endpoint', sa.String(length=300), nullable=True))
    op.add_column('blockchain', sa.Column('api_key', sa.String(length=300), nullable=True))
    op.drop_index('tx_scan_url', table_name='blockchain')
    op.create_unique_constraint(None, 'blockchain', ['api_key'])
    op.create_unique_constraint(None, 'blockchain', ['tx_hash_api_endpoint'])
    op.drop_column('blockchain', 'tx_scan_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain', sa.Column('tx_scan_url', mysql.VARCHAR(collation='utf8_unicode_ci', length=300), nullable=True))
    op.drop_constraint(None, 'blockchain', type_='unique')
    op.drop_constraint(None, 'blockchain', type_='unique')
    op.create_index('tx_scan_url', 'blockchain', ['tx_scan_url'], unique=False)
    op.drop_column('blockchain', 'api_key')
    op.drop_column('blockchain', 'tx_hash_api_endpoint')
    # ### end Alembic commands ###
